
pool:
  vmImage: 'windows-latest'

variables:
  AzurePipelines: true
  BuildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

steps:
- task: DotNetCoreInstaller@1
  inputs:
    version: '3.1.100'

- task: NuGetToolInstaller@1
  inputs:
    checkLatest: true

- task: UseDotNet@2
  displayName: "Use dotnet sdk 3.x"
  inputs:
    version: 3.x
    includePreviewVersions: false

- script: |
    dotnet tool install --tool-path . nbgv
    .\nbgv cloud
  displayName: Install NerdBank.GitVersioning

- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages
  inputs:
    command: restore
    verbosityRestore: Detailed
    projects: "src/*.sln"

- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    command: build
    arguments: --no-restore -c $(BuildConfiguration)
    projects: "src/*.sln"

- task: DotNetCoreCLI@2
  displayName: Run tests
  inputs:
    command: test
    arguments: --no-build -c $(BuildConfiguration)
    projects: "src/*.sln"

- task: CopyFiles@2
  displayName: Copy packages
  inputs:
    contents: 'Packages/$(BuildConfiguration)/*.nupkg'
    targetFolder: '$(Build.ArtifactStagingDirectory)/nugets'
    flattenFolders: true

- task: PublishPipelineArtifact@1
  displayName: Publish nuget packages
  inputs:
    artifactName: nugets
    targetPath: '$(Build.ArtifactStagingDirectory)/nugets'